#!/bin/sed -f
# Works on GNU sed 4.2.1.
#
# Reads the JSON generated by bas-out-to-json-part1.sed and fixes it.

s/[\r ]\+$//

1 {
	/^},/d
}

/^{/,/^}/ {
	# Append to the hold buffer.
	H
	/^}/ {
		s/.*//
		x

		# Discarding invalid testcases.
		/\n[^{} ]/d
		/ a: 0,.* b: 0,.* q: 0/d

		# Removing the last comma.
		s|,\n}|\n}|

		# Removing leading newline.
		s|^\n\+||

		# Changing to tab.
		s|\n  |\n\t|g

		p
	}
	d
}
